### ISSUE TITLE
Dirk Kelly Forced Push The Serfs Revert

### ISSUE THREAD

**Issue by dirkkelly** [breadtubetv/breadtubetv#147]
[Updated] Hey Everyone

In order to rush through a revert to The Serfs channel being returned I disabled admin protections and forced the merge. I should not have done this, I should I have followed best practices and agreed process of waiting for a reviewer. 

As an immediate action I reported myself (in a way which was regarded as a little to intense) and  returned the protections for the branch

Going forward I’d like to address

- an admin council
- code of conduct policy 
- a new process for content updates that allows us to respond more rapidly to the community. 
  - This is definitely the biggest issue and should have been addressed before I behaved in a non collaborative manner. 

I’m sorry for my behavior, I trust that I will learn from this and that we’ll improve our process to ensure this never happens again. 

If this website project is to be successful we must ensure that more people can modify it and respond to rapid change requests like such. 

I would like to reach out to the r/breadtube moderators to discuss building an education and onboarding process that will allow more volunteers to support the websites further development. 

I am going to discuss this change with the rest of the active development team over April and then deliver a request for support to Reddit.

**Comment by dirkkelly** [comment]
![99D7822C-D849-4E79-BF80-66ECC194F93F](https://user-images.githubusercontent.com/81055/55482048-af6ac480-55f1-11e9-8c4b-1944064dd106.png)

**Comment by dirkkelly** [comment]
Added two more admins @j16r @craiglonsdale 
![1057BB4F-3616-487A-9CF3-06914188CD5F](https://user-images.githubusercontent.com/81055/55482671-0b821880-55f3-11e9-96ef-6b3573d71bbf.png)

**Comment by dirkkelly** [comment]
Also added @jaymickey as an admin.

**Comment by j16r** [comment]
> Admit your mistakes before someone else exaggerates them
 -- Mark Twain

**Comment by craiglonsdale** [comment]
Unfortunately, I don't think there is a way for us to be able to democratically change the settings for these things. It will be an inherent flaw in GitHub that those with powers have the ability to abuse those powers.
Though we should probably come up with a system to handle the abuse of power when it shows up.
I'll try to pick up my game a bit when it comes to reviewing content, I believe if you have a position of authority (yuck) in the community it should reflect a combination work you have accomplished and value you are adding to the project.
My current laptop is just a POS work laptop, where some of the keys don't even work properly so I'll get mine repaired and make it part of my schedule to move things through the pipeline which should help alleviate this type of thing occurring into the future.
