### ISSUE TITLE
Critique of Authority 

### ISSUE THREAD

**Issue by dirkkelly** [breadtubetv/breadtubetv#20]
Import this YouTube playlist 
https://www.youtube.com/playlist?list=PL0ZkYfv_UCFblNY7xrQuDWOFktm9ade1m

Provided in this comment by [u/dextreFreeman](https://www.reddit.com/user/dextreFreeman)
https://www.reddit.com/r/BreadTube/comments/ahxwrm/breadtubetv_is_live_and_open_source_you_can_help/eejk54e

Will mean adding more channels, including Beau of the Fifth Column!

**Comment by dextreFreeman** [comment]
Did my thing.

**Comment by dirkkelly** [comment]
Completed in #32
