### ISSUE TITLE
Simplify Submission Process with Forms

### ISSUE THREAD

**Issue by dirkkelly** [breadtubetv/breadtubetv#22]
**Problem**

There's a huge learning curve in adding for content right now, channels and playlists alike.

**Potential Solution**

A simple form where the details can be filled out, then a programmer can add it and let me know.

Eventually this would just automatically make a Pull Request.

**Alternatives Considered**

https://forestry.io/ is a full platform that can sit on top of static websites, but it's a heavy solution to right now.

**Additional context**

Part of the goal of this project is to teach people more about how to use the web to communicate.

While this can seem daunting, it's also a very empowering platform with regards to anyone being able to see how the internet is built and be a part of it.

But still, submission right now is over-the-top difficult.

**Comment by dirkkelly** [comment]
@craiglonsdale is looking at using Netlify to create forms 
https://www.netlify.com/docs/form-handling/

**Comment by awilson739** [comment]
Do we want a script that takes input and then modifies the channel.yaml or playlist.yaml (something in python or go)? Or do we want a link that leads to a form?

**Comment by dirkkelly** [comment]
@awilson739 This issue is referring to the forms that end users will use, I have added this to the [Submission Forms Project](https://github.com/breadtubetv/breadtubetv/projects/6?add_cards_query=is%3Aopen) and assigned this to @craiglonsdale. Please let us know if you'd like to help out.

We also need developer side scripts and we have put together another [project](https://github.com/breadtubetv/breadtubetv/projects/5) for this.
