### ISSUE TITLE
Breadtube needs a listed privacy policy.

### ISSUE THREAD

**Issue by Murodese** [breadtubetv/breadtubetv#43]
Required for use in OAuth policies, but also useful for users. Realistically, going to be something like "all personal data is stored locally" etc, but may also need to talk about Netlify's HTTP logs (if any).

**Comment by dirkkelly** [comment]
Righto, I've assigned this to myself. Let me know if there's a deadline I should be working towards.

**Comment by quietlemon** [comment]
> Netlify's HTTP logs

Indeed, your own privacy policy needs to take into account your host's privacy policy. Of course, the best is to setup your own server with logging disabled or have the wesite hosted [by some comrades](https://riseup.net/en/security/resources/radical-servers) or some nice webhosting coop.

Also worth mentioning, a static website is very easy to distribute over onion services for Tor (encrypted and authenticated) as well as IPFS (authenticated but unencrypted p2p). If that's of interest to you i may open another issue with more information about this.

Distributing your site over multiple channels makes it harder to censor and advertises practical cyber-anarchism. It's digital propaganda of the deed :fire:

**Comment by dirkkelly** [comment]
Have started putting together a privacy policy https://github.com/breadtubetv/breadtubetv/pull/157
