### ISSUE TITLE
Disable Pull Requests on sleepy-hodgkin-4b65d8

### ISSUE THREAD

**Issue by dirkkelly** [breadtubetv/breadtubetv#46]
Having 2 servers building pull requests is confusing for developers, please disable PRs on any additional servers created.

![screen shot 2019-01-23 at 9 24 16 pm](https://user-images.githubusercontent.com/81055/51609520-50376680-1f55-11e9-9ad0-59447442a3c3.png)

**Comment by craiglonsdale** [comment]
@dirkkelly  Ok I have disabled depoly previews for pull requests

**Comment by dirkkelly** [comment]
Cheers @craiglonsdale
