### ISSUE TITLE
Final tiles expand to fill entire screen

### ISSUE THREAD

**Issue by j16r** [breadtubetv/breadtubetv#58]
**Describe the bug**

The final two channels are displayed quite ... er... large.

**To Reproduce**

If I browse to the home page and scroll to the bottom, shit gets all non euclidean nameless horror from the void below.

**Expected behavior**

I'd probably say that all the tiles should be consistently sized.

**Screenshots**

<img width="1892" alt="screen shot 2019-01-27 at 18 04 00" src="https://user-images.githubusercontent.com/344071/51809413-f5a45000-225d-11e9-9046-48da1b3b3589.png">

**Desktop (please complete the following information):**

 - OS: Mac OS X Mojave
 - Browser: Firefox.
 - Version: Nightly

**Comment by dirkkelly** [comment]
Fixed in #55. Thanks!
