### ISSUE TITLE
2019 Jan Bootstrap-less Layout Redesign

### ISSUE THREAD

**Issue by dirkkelly** [breadtubetv/breadtubetv#61]
**New layout has been suggested by a discord user**

https://codepen.io/stjn/full/GzZZPp Scribbled something like this (sorry descriptions are lorem-ipsumed, was going by old code), it’s more reformist than revolutionary, but no Bootstrap or Fontawesome (only one icon used though, but that can be reformed later with some SVGs instead of an icon font).

<img width="1088" alt="screen shot 2019-01-28 at 3 01 54 pm" src="https://user-images.githubusercontent.com/81055/51819525-b1708880-230d-11e9-9a94-1d6d41fcf19a.png">

<img width="1091" alt="screen shot 2019-01-28 at 3 02 05 pm" src="https://user-images.githubusercontent.com/81055/51819538-bb928700-230d-11e9-8f43-24bf683e7211.png">

## Features

- Removes Bootstrap Framework
  - ⚠️ Will require playlists update
- Removes Font Awesome Framework
  - ⚠️ Will require playlists update
- Updates order of layout
  - ✅ Horizontal and easy to read page title
  - ✅ Website description
  - ✅ Single top level navigation 
  - ✅ Nice relevant color scheme
  - ✅ Easy call to action button
  - ✅ Underline for all links
  - ✅ Footer explanation
  - ⚠️ No fixed header
  - ⚠️ Will require playlists update
  - ⚠️ Social is at bottom of page
- Channel Card Design
  - ✅ Entirely clickable
  - ✅ Hover shows 
  - ✅ Image resizes within the container
  - ✅ Responsive design
  - ⚠️ Screen not always filled at all resolutions (current issue anyway)

## Recommendation

I can turn this into the layout for the website and make some updates to the playlist page to fit with what's currently there. 

I can extend the design to keep the site title and navigation fixed, hide the description on scroll

## Requirements

I'd just like other developers to have a look through and see if they find any usability issues that we should address in the redesign.

Let me know if there are any objections to this design.

**Comment by dirkkelly** [comment]
@breadtubetv/developers let me know your thoughts, I'll look into this in a couple of hours.

**Comment by craiglonsdale** [comment]
Yeah I'm really liking this design. I would be more than happy to drop the Bootstrap stuff. THe top needs to be sticky i think, or maybe have some CSS/JS to hide it on fast down scroll and scroll it back in when you scroll up.
I think this looks like a positive change :)

**Comment by dirkkelly** [comment]
this was merged in #72
