### ISSUE TITLE
Questions re: scripts and project organization

### ISSUE THREAD

**Issue by soliveira-vouga** [breadtubetv/breadtubetv#68]
Should we be storing scripts in a separate repo (as the one I created) or do we want to make this repo a monorepo and just store all of our scripts here?

I'm not too familiar with Netlify so I'm not sure how best to work with it in terms of repo organization.

For example, I can make that /r/breadtube script run as a lambda function but I'm not sure how this would be done with Netlify nor how we can have that data be used by the main site.

Another example would be a script that periodically updates the subscription numbers and we can store that in a separate yaml file that would be an array of channels with each item containing the slug and # of subscriptions.

**Comment by dirkkelly** [comment]
We have some script development in progress here https://github.com/breadtubetv/breadtubetv/issues/68 

Hoping that we can have local copies of scripts in Go that we can then execute as lambdas.

This example script updates an entire specified channel, we could have one that can update all channels subscription numbers by rewriting `data/channels`

**Comment by soliveira-vouga** [comment]
Okay, I'll remove the other repo and keep the scripts in this one
