### ISSUE TITLE
bake channel update

### ISSUE THREAD

**Issue by dirkkelly** [breadtubetv/breadtubetv#88]
**Is your feature request related to a problem? Please describe.**

As a content developer I need to update the subscriber counts of all channels, this is an overwhelming task to do one at a time

**Describe the solution you'd like**

Running the command `bake channel update` would do a fresh import of the youtube data of every channel listed in `data/channels`, as if you'd run `bake channel import SLUG youtube URL` on each channel.

As the files are going to be in different structures, it will need to match on either the `providers.youtube.url` or the `url`, at least until every file has been updated. I can update them all individually if dealing with the multiple data structures is a pain.

**Additional context**

This is a stretch goal that came out of https://github.com/breadtubetv/breadtubetv/pull/51

It would be good to have this handled in another PR

**Comment by dirkkelly** [comment]
@jaymickey let me know if this sounds like something you'd like to do.

**Comment by jaymickey** [comment]
@dirkkelly Yep, happy to pick it up.

**Comment by dirkkelly** [comment]
This exists now and it's awesome :D
